# ==========================================
# SPRING APPLICATION CONFIGURATION
# ==========================================
spring.application.name=ORDER-SERVICE
server.port=8082
server.servlet.context-path=/api

# H2 Database Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 In-Memory Database Configurations
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================================
# EUREKA SERVICE DISCOVERY CONFIGURATION
# ==========================================
# Enables the verification check of Spring Cloud compatibility
spring.cloud.compatibility-verifier.enabled=false

# Re-enable Eureka discovery registration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ROUTING FIX: Routes container traffic safely back to the Eureka Server on your desktop
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
